### ISSUE TITLE
@guarded requires an expression... (v0.7.0)

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGraphics/Gtk.jl#359]
I cannot get the following sample to work on Julia v0.7.0:

```
using Gtk, Graphics
c = @GtkCanvas()
win = GtkWindow(c, "Canvas")
@guarded draw(c) do widget
    ctx = getgc(c)
    h = height(c)
    w = width(c)
    # Paint red rectangle
    rectangle(ctx, 0, 0, w, h/2)
    set_source_rgb(ctx, 1, 0, 0)
    fill(ctx)
    # Paint blue rectangle
    rectangle(ctx, 0, 3h/4, w, h/4)
    set_source_rgb(ctx, 0, 0, 1)
    fill(ctx)
end
show(c)
```

I get the following error (Ubuntu 18.04):
```
ERROR: LoadError: LoadError: @guarded requires an expression defining a function
```

...Will try to solve it myself, but not the best with macros.

**Comment by tknopp** [comment]
:-) @ma-laforge you found the one case where we cheated and disabled the tests.

The issue is (I think) that the expression for do block has changed and in turn the macro has an issue. The workaround is to write this without the do block.

@JeffBezanson @timholy: Do some of you know what changed to do blocks? The macro in question is here:
https://github.com/JuliaGraphics/Gtk.jl/blob/46f5cb4ec1f83fd8f8f4e80c04d7564774de2402/src/base.jl#L61
I don't speak macro so would appreciate a fix.

**Comment by tknopp** [comment]
Here is the change:

before
```
f(x) do a,b
    body
end
parses as (call f (-> (tuple a b) (block body)) x).
```

after
```
do syntax:

f(x) do a,b
    body
end
parses as (do (call f x) (-> (tuple a b) (block body))).
```

**Comment by tknopp** [comment]
towards becoming a macro-ninja ... ;-)

**Comment by ma-laforge** [comment]
Thanks.  It works perfectly now.

**Comment by tknopp** [comment]
yep, I actually needed that pattern in Winston.jl, which now also work in Julia 0.7. Thanks for reporting the bug. I am so happy that Gtk is now 0.7 ready.
