### ISSUE TITLE
how to get content of GtkTextView?

### ISSUE THREAD

**Issue by jitavi** [JuliaGraphics/Gtk.jl#399]
Note: this ticket is more a documentation issue than an code issue.

If you create a text area widget: `ta = GtkTextView()`

How can you get the text typed by the user in this widget ?

Method to get text in a GtkEntry does not work for GtkTextView: `get_gtk_property(ta,:text,String)`

Using generic search method: `methodswith(GtkTextView)`  shows two methods insert! and splice!. They are not useful to retrieve widget content .

Could you put an example in textwidgets.md or in the directory example ? This would also be useful to show the available signals for this widget.

**Comment by tknopp** [comment]
```
using Gtk.ShortNames
textBuf = TextBuffer()
textView = TextView(textBuf)
win = Window(textView)
G_.text(textBuf, "Test", -1)
showall(win)
```
i.e. the viewing widget in Gtk is separated from the actual text buffer.

**Comment by vtjnash** [comment]
Or more typically perhaps: `.buffer[GObject].text[String]`

As tknopp mentions, the text object is independent from the renderer. Basically a direct translation from https://developer.gnome.org/gtk3/stable/GtkTextView.html

**Comment by jitavi** [comment]
Example from tknopp is to set text area content; from it I start to find how getting the text content could look like:

```
tb = GtkTextBuffer()
# set the content
G_.text(tb, "test", -1)
sIter = G_.start_iter(tb)
eIter = G_.end_iter(tb)
# get the content
println(G_.text(tb, sIter, eIter, false))
```

It fails on the last line, I was expecting to match method `text(::GtkTextBuffer, ::Any, ::Any, ::Any) at /home/jitavi/.julia/packages/Gtk/ADDrn/gen/gbox3:4542`

The match fails because type of tb is `GtkTextBufferLeaf` instead of `GtkTextBuffer`
The function GtkTextBuffer looks like a constructor of the struct GtkTextBuffer but is not one sadly.

The way is very difficult when there is no doc for a widget:

- there is no javadoc like and generic API browsing (using methodswith) miss important parts of the API (GAccessor for example)
- Gtk documentation is not enough to complete Gtk Julia documentation : if I imagine, I write C++, I read Gtk documentation then I  search in Julia wrapper where is wrapped the C++ function I need, but the code of the wrapper is very difficult to understand, there are many mechanism to understand in the wrapper, that are well hidden when you use a documented widget

Maybe, it is too early to use the wrapper for developer without Julia C++ wrapping ?

**Comment by tknopp** [comment]
The Gtk bindings for Julia are certainly not in the same state as gtmm, which have full-time developers working on them. The primary issue is that since about 3 years, the project is more or less maintainer less. I keep it up running (and have migrated it to 1.0) since I use Gtk.jl actively. But I don't have the resources improving Gtk.jl much.

Having said that I tend to say that its not that difficult to use (and extend Gtk.jl) if you are willing to work with the current state as is. I would say that most things are possible, some require extending Gtk.jl itself. 

Regarding `TextBuffer` you might want to have a look at
https://github.com/jonathanBieler/GtkIDE.jl
of ping @jonathanBieler who has more experience with the text widgets than me.

**Comment by tknopp** [comment]
One comment to `GtkTextBuffer`. Yes `GtkTextBuffer` is an abstract type with `GtkTextBufferLeaf` being the concrete type. The issue being solved here is that Julia does not support multiple inheritance while Gtk/C does. The above concept is a workaround for this.

**Comment by tknopp** [comment]
And here is a quick solution that involves no buffers:
```
get_gtk_property(tb, :text, String)
```
In general I found it much easier to work with the property system of Gtk, instead of the accessors that go through the `GAccessor` module. 
We recently introduced the following syntax for properties:
```
tb.text[String]
```
This is the same as `get_gtk_property(tb, :text, String)`

**Comment by tknopp** [comment]
closing this since it is not really an issue but more a question
