### ISSUE TITLE
Displaying a 2d RGB24 array

### ISSUE THREAD

**Issue by kraftpunk97** [JuliaGraphics/Gtk.jl#422]
Hello. I have a `Array{RGB24, 2}`. How do I paint it on my GtkCanvas?

**Comment by TravisA9** [comment]
Hello, I was trying to find out pretty much the same thing last night. After not finding any documentation at all on it I ended up systematically testing many possibilities and ended up with this:

```julia

    img = rand(UInt32,150,150)
    image(ctx, CairoRGBSurface(img), 0, 0, 150,150)


```

**Comment by TravisA9** [comment]
It would be awesome if we could help out with the documentation of Cairo. I have noticed that many look for documentation and it's sparse to nonexistent.

Here's the complete code for my test:

```julia

using Gtk, Gtk.ShortNames, Graphics, Images, Cairo, Colors

c = Canvas(600,400)
win = Window(c, "Canvas")

@guarded draw(c) do widget
    ctx = getgc(c)
    buf = rand(UInt32,150,150)
    image(ctx, CairoRGBSurface(buf), 0, 0, 150,150)
end
show(c)
```

*may or may not be using all of the ``` using[s]```

**Comment by lobingera** [comment]
Cairo.jl follows (if feature is implemented) the libcairo C-API and this is documented in https://www.cairographics.org/documentation/ 
What are you missing?

**Comment by TravisA9** [comment]
I have never used Cairo before using julia and the examples and documentation is sometimes less helpful to me than just reading through the julia code and trying to interpret what is happening there. I may be alone in this but applying the documentation or code examples that may be written in C++ or other is not the same as reading julia-specific documentation. I do appreciate the [examples](https://github.com/JuliaGraphics/Cairo.jl/tree/master/samples) written in julia that show how to do a few things. Sometimes the issue is knowing how to get Cairo to work with GTK or other things. So, to answer your question @lobingera , *what I'm missing*, is a smooth transfer of the knowledge in the documentation to the context of julia. For example, for me it is sometimes difficult to determine which function in the Cairo documentation is the equivalent function in Cairo.jl, although many of the names are similar enough to figure out easily. I think that Cairo.jl is well thought out and  implemented and I am very grateful to be able to use it instead of trying to roll my own. 

Thank you for taking my thoughts into consideration! 

[This is what I have been doing](https://travisa9.github.io/NaquadahBrowser/) with Cairo.jl  ...I hope someday it will be useful :)

**Comment by vtjnash** [comment]
You can also access the backing object directly for a GtkImage, as shown in this example:
https://github.com/JuliaGraphics/Gtk.jl/blob/636d0fea2c83159b930aad632dbbac54f926c833/test/gui.jl#L302-L306

You re-render updates by re-assigning the image property, causing it to mark that region as dirty and repaint it.

**Comment by lobingera** [comment]
@TravisA9 I see. I can only recommend for you to contribute own solutions to the Gtk.jl documentation.

**Comment by kraftpunk97** [comment]
Thanks @TravisA9 @lobingera @vtjnash. @TravisA9 's solution works better for my use case, because depending upon the user, my program may have to paint either in Juno's plot pane, or draw up a separate window and paint in that. Closing issue...
