### ISSUE TITLE
Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/Gtk.jl#458]
When I load Gtk I see the following warnings:
```julia
julia> using Gtk
Gtk-Message: 20:15:48.288: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:15:48.288: Failed to load module "canberra-gtk-module"
```
However, the tests pass.

**Comment by giordano** [comment]
We notices these warnings when we first built Gtk, they should be harmless.  canberra-gtk-module is a module to manage sound events: https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed

**Comment by timothywalsh** [comment]
This issue is causing problems for me too.

I am new to Gtk.jl so working through the example code here https://juliagraphics.github.io/Gtk.jl/latest/manual/gettingStarted/

If I save the code as a file and try to run it by
`>julia first_GTK_app.jl`
I get the error 
`Gtk-Message: 13:10:34.934: Failed to load module "canberra-gtk-module"`
and no window appears

However, if I execute the same code from within the Julia REPL, I get the same error message, and the window does appear.

Any ideas how to get around this?

**Comment by tknopp** [comment]
These are two different things. The window not appearing in the non-REPL mode is correct. You need to stop Julia from quitting, see https://juliagraphics.github.io/Gtk.jl/latest/manual/nonreplusage/

The other thing is not an error but a warning about the theme. I see this as well on ubuntu.

**Comment by timothywalsh** [comment]
Ah, okay. Thanks for the explanation. I just got the warning and then Julia quit without anything happening, so I assumed they were related.

**Comment by tknopp** [comment]
It actually is a feature rather than a bug. In other Gtk bindings, one has to go into the blocking main loop and cannot further interact within the REPL. In this way we have full flexibility.

**Comment by alexandrelevada** [comment]
I was annoyed with this message all the time and what solved for me was to create an enviroment variable and export it in .bashrc

export GTK_PATH"=/usr/lib/x86_64-linux-gnu/gtk-3.0:$PATH"      (or gtk-2.0 if it is your version)

Julia 1.6 running in Ubuntu 20.04

Hope it helps

**Comment by oblivia-simplex** [comment]
This fixed it, thanks!

**Comment by ufechner7** [comment]
When using this workaround with Julia 1.7.3 on Ubuntu 18.04:
```
export GTK_PATH"=/usr/lib/x86_64-linux-gnu/gtk-3.0:$PATH"
```
together with InspectDR the warnings disappear, but in addition the menu is not shown any longer.

Any idea?
