### ISSUE TITLE
Fails on 1.5

### ISSUE THREAD

**Issue by KristofferC** [JuliaGraphics/Gtk.jl#511]
```
Simple grayscale: Error During Test at /home/pkgeval/.julia/packages/ImageView/Pi4jH/test/simple.jl:5
  Got exception outside of a @test
  could not load symbol "jl_function_ptr":
  /opt/julia/bin/../lib/libjulia.so.1: undefined symbol: jl_function_ptr
```

**Comment by jonathanBieler** [comment]
Looks like some major redesign are needed then : #358

**Comment by KristofferC** [comment]
Maybe `@cfunction` could be used?

**Comment by jonathanBieler** [comment]
It's what @tknopp was trying to do yes, but it doesn't seem so straighforward.

**Comment by tknopp** [comment]
Thanks for picking up that thread Jonathan, which indeed describes what I have done when migrating Gtk.jl to 1.0. If I recall correctly it was not possible to just use `@cfunction`. What is needed is that all functions above that (in Gtk.jl) are converted to macros, i.e. that the user interface is a macro. Another option would be to remove that `signal_connect` function entirely and use the other once, where IIUC the Julia callback is put into a closure and then called. 

We should discuss the up and downsides to this. IIUC the closure thingy is in principle ok, but we have the slow down due to variable capturing. I am using mostly the closure captured `signal_connect` and see extreme long time during compile time (my app takes more than 1 minute when I press certain buttons).
