### ISSUE TITLE
GtkSpinner doesn't appear.

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaGraphics/Gtk.jl#604]
```julia
using Gtk

win = GtkWindow("Spin Test")
spin = GtkSpinner()
push!(win, spin)
showall(win)

Gtk.start(spin)
```

The spinner doesn't show up. It also doesn't show up if I build the UI in Glade (where it works fine) and load the UI that way. Both Linux (via WSL) and Windows. Am I missing something?

**Comment by BioTurboNick** [comment]
Looks related to part of #525

**Comment by jwahlstrand** [comment]
The SVG pixbuf loader included in Librsvg_jll is installed in a different directory than the one where gdk_pixbuf_jll installs its loaders. Gtk.jl is using the latter directory. I copied the librsvg loader "libpixbufloader-svg.so" into the directory where Gtk.jl is looking and (after helping it find libbz2 and deleting Gtk.jl's MutableArtifacts.toml so the cache is regenerated) GtkSpinner works. So it appears this is indeed an SVG issue.

It looks like gdk-pixbuf-query-loaders only looks in one directory, so not sure this can be fixed in Gtk.jl.

**Comment by BioTurboNick** [comment]
How did you track down the directories?

**Comment by jwahlstrand** [comment]
The directory where Gtk looks for the pixbuf loaders is stored in `gdk_pixbuf_jll.gdk_pixbuf_loaders_dir_path`, and the path of the Librsvg loader is in `Librsvg_jll.libpixbufloader_svg`. Maybe one could copy these files into a new directory and use that.

However there seems to be a build issue with gdk_pixbuf_jll. I'll open an issue about that today.

**Comment by BioTurboNick** [comment]
Ah I see. I suppose the underlying issue is that artifact directories can't find each other?

**Comment by jwahlstrand** [comment]
Yeah, the querying program expects everything to be in one folder. One option would be for Gtk.jl to copy (or symlink) the loaders into its own directory and then run the query. But the issue with gdk_pixbuf_jll + Librsvg_jll needs fixing first...

**Comment by BioTurboNick** [comment]
Linking to #605 , which appears to fix this.
